// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3RWAMaIx883LRf8_MfE70izSUFZzYcDM',
    appId: '1:909775527453:web:1afa4ae7ad3732e553b0f4',
    messagingSenderId: '909775527453',
    projectId: 'movie-app-9db3f',
    authDomain: 'movie-app-9db3f.firebaseapp.com',
    storageBucket: 'movie-app-9db3f.appspot.com',
    measurementId: 'G-2BNMK2R3RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIdH4OV0VtBLPfr6Yi_FO6SzOnK7KwtHg',
    appId: '1:909775527453:android:dd44c91646a3838f53b0f4',
    messagingSenderId: '909775527453',
    projectId: 'movie-app-9db3f',
    storageBucket: 'movie-app-9db3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVDrxi7DKWGeCHqRh0R_Mcip1ETNBLX_w',
    appId: '1:909775527453:ios:c2d1f6785ac08a6553b0f4',
    messagingSenderId: '909775527453',
    projectId: 'movie-app-9db3f',
    storageBucket: 'movie-app-9db3f.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVDrxi7DKWGeCHqRh0R_Mcip1ETNBLX_w',
    appId: '1:909775527453:ios:b472125d7597bffc53b0f4',
    messagingSenderId: '909775527453',
    projectId: 'movie-app-9db3f',
    storageBucket: 'movie-app-9db3f.appspot.com',
    iosBundleId: 'com.example.moviesApp.RunnerTests',
  );
}
