// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvdsc2g7xc1KloHaXbQ45M9tH8mI9aAWw',
    appId: '1:420254640768:web:0629222f7734ccda159465',
    messagingSenderId: '420254640768',
    projectId: 'moviesapp-8d9f3',
    authDomain: 'moviesapp-8d9f3.firebaseapp.com',
    storageBucket: 'moviesapp-8d9f3.appspot.com',
    measurementId: 'G-BRB4KHX5FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB91I_uhSZVAgAJmLkXuJW0BkekMuHzX5A',
    appId: '1:420254640768:android:371927d76fbb2018159465',
    messagingSenderId: '420254640768',
    projectId: 'moviesapp-8d9f3',
    storageBucket: 'moviesapp-8d9f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNJiC2Omv8CUMIWNfp1Uat7sgSOrtkjiw',
    appId: '1:420254640768:ios:3e7efa14c3df5877159465',
    messagingSenderId: '420254640768',
    projectId: 'moviesapp-8d9f3',
    storageBucket: 'moviesapp-8d9f3.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNJiC2Omv8CUMIWNfp1Uat7sgSOrtkjiw',
    appId: '1:420254640768:ios:5b7d892d41e56ef5159465',
    messagingSenderId: '420254640768',
    projectId: 'moviesapp-8d9f3',
    storageBucket: 'moviesapp-8d9f3.appspot.com',
    iosBundleId: 'com.example.moviesApp.RunnerTests',
  );
}
